"""Heptadecagon (17-gon) and constructible polygons."""

import math
import cmath
from typing import List, Tuple
import numpy as np

__all__ = [
    'gaussian_periods', 'cos_2pi_over_17_value',
    'constructible_ngons', 'fermat_primes', 'is_fermat_prime', 'is_constructible',
    'heptadecagon_exact',
]
from python.disquisitiones import cyclotomic_poly, heptadecagon_vertices, cos_2pi_over_17
from python.modular import primitive_root


# ======================================================================
# Gauss periods
# ======================================================================

def gaussian_periods(p: int, length: int) -> List[complex]:
    """Compute Gaussian periods for prime p.
    
    Periods of given length are sums of roots of unity with indices
    in the same coset of the subgroup of (Z/pZ)* generated by g^length.
    """
    g = primitive_root(p)
    zeta = cmath.exp(2j * math.pi / p)
    
    # Generate all powers of g modulo p
    powers = []
    cur = 1
    for _ in range(p - 1):
        powers.append(cur)
        cur = (cur * g) % p
    
    periods = []
    for start in range(length):
        period = sum(zeta**powers[start + k*length] for k in range((p-1)//length))
        periods.append(period)
    
    return periods


def cos_2pi_over_17_value() -> float:
    """Numerical value of cos(2π/17)."""
    return math.cos(2 * math.pi / 17)


def constructible_ngons(limit: int = 100) -> List[int]:
    """List of n for which regular n-gon is constructible.

    n = 2^k * p1 * p2 * ... * pm where pi are distinct Fermat primes.
    """
    if limit <= 0:
        return []
    fermat_primes = [3, 5, 17, 257, 65537]
    constructible = set()

    for k in range(int(math.log2(limit)) + 2):
        base = 2 ** k
        if base > limit:
            break
        
        # Add base
        if base <= limit:
            constructible.add(base)
        
        # Multiply by products of Fermat primes
        def add_products(current, start_idx):
            if current > limit:
                return
            if current > 0:
                constructible.add(current)
            for i in range(start_idx, len(fermat_primes)):
                add_products(current * fermat_primes[i], i + 1)
        
        add_products(base, 0)
    
    return sorted(constructible)


def fermat_primes() -> List[int]:
    """Known Fermat primes."""
    return [3, 5, 17, 257, 65537]


def is_fermat_prime(n: int) -> bool:
    """Check if n is a known Fermat prime."""
    return n in [3, 5, 17, 257, 65537]


def is_constructible(n: int) -> bool:
    """Check if regular n-gon is constructible."""
    # Remove factors of 2
    while n % 2 == 0:
        n //= 2
    
    # Check if remaining is product of distinct Fermat primes
    for p in [3, 5, 17, 257, 65537]:
        if n % p == 0:
            n //= p
            if n % p == 0:  # not distinct
                return False
    
    return n == 1


# ======================================================================
# Exact expressions for 17-gon
# ======================================================================

def heptadecagon_exact() -> dict:
    """Exact expressions for 17-gon construction."""
    sqrt17 = math.sqrt(17)
    
    # Gaussian periods of length 8
    eta1 = (-1 + sqrt17) / 2
    eta2 = (-1 - sqrt17) / 2
    
    # Periods of length 4
    # μ1 + μ2 = η1, μ1*μ2 = -1
    # μ3 + μ4 = η2, μ3*μ4 = -1
    sqrt_eta1_sq_4 = math.sqrt(eta1**2 + 4)
    mu1 = (eta1 + sqrt_eta1_sq_4) / 2
    mu2 = (eta1 - sqrt_eta1_sq_4) / 2
    
    sqrt_eta2_sq_4 = math.sqrt(eta2**2 + 4)
    mu3 = (eta2 + sqrt_eta2_sq_4) / 2
    mu4 = (eta2 - sqrt_eta2_sq_4) / 2
    
    # Periods of length 2
    # ν1 + ν2 = μ1, ν1*ν2 = μ3
    # ν3 + ν4 = μ2, ν3*ν4 = μ4
    # ν5 + ν6 = μ3, ν5*ν6 = μ1
    # ν7 + ν8 = μ4, ν7*ν8 = μ2
    
    # These give the cosines
    cos_2pi_17 = mu1 / 2
    cos_4pi_17 = mu2 / 2
    cos_8pi_17 = mu3 / 2
    cos_16pi_17 = mu4 / 2
    
    return {
        'eta1': eta1, 'eta2': eta2,
        'mu1': mu1, 'mu2': mu2, 'mu3': mu3, 'mu4': mu4,
        'cos_2pi_17': cos_2pi_17,
        'cos_4pi_17': cos_4pi_17,
        'cos_8pi_17': cos_8pi_17,
        'cos_16pi_17': cos_16pi_17,
    }


if __name__ == "__main__":
    print("=== Heptadecagon Demo ===")
    
    # Constructible polygons
    print("\nConstructible n-gons up to 100:")
    print(constructible_ngons(100))
    
    # 17-gon vertices
    print("\n17-gon vertices (first 5):")
    verts = heptadecagon_vertices()
    for i, (x, y) in enumerate(verts[:5]):
        print(f"  V{i}: ({x:.6f}, {y:.6f})")
    
    # Exact expressions
    print("\nExact cosines:")
    exact = heptadecagon_exact()
    for key, val in exact.items():
        print(f"  {key} = {val:.10f}")
    
    # Verify
    print(f"\ncos(2π/17) = {cos_2pi_over_17_value():.10f}")
    print(f"cos(2π/17) exact = {exact['cos_2pi_17']:.10f}")
    print(f"Difference = {abs(cos_2pi_over_17_value() - exact['cos_2pi_17']):.2e}")